title:              김우석
email:              eypk9673@naver.com
description:        Clean Blog
author:             KIM WOO SEOK
baseurl:            "/"
url:                "https://kimwoo123.github.io"

# Social Profiles
twitter_username:   
github_username:    kimwoo123
facebook_username:  eypk9673
instagram_username:  eypk9673
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
